name: PR Duplicator

on:
  pull_request:
    types: [closed]
    branches:
      - master
jobs:
  pr_duplicator:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - run: npm install
    - name: PR Duplicator
      uses: ./.github/actions/pr_duplicator
      with:
        from: 'pr_duplicator_test'
        base: 'master'
        to: 'pr_duplicator_test_to'
        pr_author: 'tiblu'
        github-token: ${{ secrets.GITHUB_TOKEN }}